[package]
name = "ui_test_dep_bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]

exclude = [
    "crates/compile_test"
]

members = [
    "crates/*"
]
